In [3]:
# Practice All syllabus

In [4]:
import numpy as np

In [8]:
arr1D =np.array([1,3,5,6,7])

In [9]:
arr1D

array([1, 3, 5, 6, 7])

In [11]:
arr2D = np.array([[1,3,5,6,8],[4,5,6,8,7]])

In [14]:
arr2D
arr2D.ndim

2

In [119]:
arr3D= np.array([[[1,3,5,6,8],[4,5,6,8,7],[7,8,9,5,6]],[[7,8,9,5,6],[7,8,9,5,6],[7,8,9,5,6]],[[1,3,5,6,8],[4,5,6,8,7],[7,8,9,5,6]]])
arr3D

array([[[1, 3, 5, 6, 8],
        [4, 5, 6, 8, 7],
        [7, 8, 9, 5, 6]],

       [[7, 8, 9, 5, 6],
        [7, 8, 9, 5, 6],
        [7, 8, 9, 5, 6]],

       [[1, 3, 5, 6, 8],
        [4, 5, 6, 8, 7],
        [7, 8, 9, 5, 6]]])

In [123]:
print(arr3D.ndim)
print((arr3D>5) & (arr3D<8))

3
[[[False False False  True False]
  [False False  True False  True]
  [ True False False False  True]]

 [[ True False False False  True]
  [ True False False False  True]
  [ True False False False  True]]

 [[False False False  True False]
  [False False  True False  True]
  [ True False False False  True]]]


In [124]:
(arr3D>2) & (arr3D < 7)

array([[[False,  True,  True,  True, False],
        [ True,  True,  True, False, False],
        [False, False, False,  True,  True]],

       [[False, False, False,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False,  True,  True]],

       [[False,  True,  True,  True, False],
        [ True,  True,  True, False, False],
        [False, False, False,  True,  True]]])

In [76]:
arr1D[1:3] ## start from 1st index till before 3rd index (means 1 and 2 index)

array([3, 5])

In [78]:
arr3D

array([[[1, 3, 5, 6, 8],
        [4, 5, 6, 8, 7],
        [7, 8, 9, 5, 6]]])

In [88]:
arr3D.ndim

3

In [26]:
arr2D[1][1:3] # first index (mean 1st index kay column k 1st ondex to 2 index )

array([5, 6])

In [83]:
arry = np.random.randint(1,10,10) ## 1 say lay kar 10 tak and their will 10 column

In [84]:
arry

array([3, 3, 3, 7, 2, 2, 9, 1, 4, 5])

In [58]:
arry.reshape(5,2) ## reshaping 

array([[5, 8],
       [3, 5],
       [5, 4],
       [7, 2],
       [7, 9]])

In [125]:
# Next Assignment

In [127]:
# Data Frame

In [135]:
import pandas as pd

In [136]:
arr2D

array([[1, 3, 5, 6, 8],
       [4, 5, 6, 8, 7]])

In [137]:
frame2d= pd.DataFrame(arr2D)

In [138]:
frame2d

0  1  2  3  4
0  1  3  5  6  8
1  4  5  6  8  7

In [158]:
dic= {"Ai for EO":[90,89,87,81,76,78,79,90,71,67],
      "Python1":[67,87,56,75,81,90,67,45,98,67],
      "Python2":(78,89,76,78,56,98,45,71,70,45),
      "Games":["in","out","in","out","in","out","in","out","in","out"]
      
     }
studentName = ["Ali","Ahmed","Nasir","Asad","Khan","Saad","Fahad","Usman","Talha","Fazal"]

In [159]:
data = pd.DataFrame(dic,index=studentName)

In [160]:
data

Ai for EO  Python1  Python2 Games
Ali           90       67       78    in
Ahmed         89       87       89   out
Nasir         87       56       76    in
Asad          81       75       78   out
Khan          76       81       56    in
Saad          78       90       98   out
Fahad         79       67       45    in
Usman         90       45       71   out
Talha         71       98       70    in
Fazal         67       67       45   out

In [161]:
 data.reindex(['a', 'b', 'c', 'd', 'e'])

Ai for EO  Python1  Python2 Games
a        NaN      NaN      NaN   NaN
b        NaN      NaN      NaN   NaN
c        NaN      NaN      NaN   NaN
d        NaN      NaN      NaN   NaN
e        NaN      NaN      NaN   NaN

In [166]:
data.reindex(["Talha","Fazal"])

Ai for EO  Python1  Python2 Games
Talha         71       98       70    in
Fazal         67       67       45   out

In [168]:
# List of Dict
dic= [{"Ai for EO",90,89,87,81,76,78,79},
      {"Python1",67,87,56,75,81,90,67}]

In [172]:
data2 = pd.DataFrame(dic)

In [170]:
data2

0   1   2   3   4   5        6     7
0  Ai for EO  76  78  79  81  87       89  90.0
1         67  75  81  87  56  90  Python1   NaN

In [173]:
listOfList = [[1,2,3,3],[4,5,6,7]]

In [174]:
data3 = pd.DataFrame(listOfList)

In [175]:
data3

0  1  2  3
0  1  2  3  3
1  4  5  6  7

In [176]:
data3 = pd.DataFrame(listOfList)

In [177]:
data3

0  1  2  3
0  1  2  3  3
1  4  5  6  7