In [101]:
import numpy as np


### nd Array

In [102]:
x =np.zeros((4,4)) # 4 ROWs and 4 Columns
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
x = np.ones((1,2)) #1 Row and 1 Columns
x

array([[1., 1.]])

In [104]:
x = np.empty((4,6))
x

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 7.56602524e-307,
        8.45559303e-307, 8.06612616e-308, 6.89810244e-307],
       [1.22387550e-307, 2.22522596e-306, 8.34423917e-308,
        1.11261162e-306, 1.78021527e-306, 2.46155235e-312]])

In [105]:
ls = [1,4,5,6]
x= np.array(ls)
x

array([1, 4, 5, 6])

In [106]:
x = np.arange(1,100,10) # prameters start stop step
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [107]:
x.shape # 10 elements ki ake array hai with 1 dimensional array

(10,)

In [108]:
x= np.empty((10,10))
x.shape

(10, 10)

In [109]:
x.reshape((2,50)) # their are 100 elements need mulipules of 100 (2,50),(2,2,5,5)

array([[1.33021921e-311, 0.00000000e+000, 1.69759695e-313,
        4.94065646e-324, 1.33021924e-311, 5.92878775e-323,
        1.33021921e-311, 2.33419569e-313, 0.00000000e+000,
        0.00000000e+000, 1.31421462e-321, 0.00000000e+000,
        2.75859485e-313, 4.94065646e-324, 1.33021924e-311,
        1.08694442e-322, 1.33021921e-311, 3.60739317e-313,
        0.00000000e+000, 0.00000000e+000, 1.50690022e-321,
        0.00000000e+000, 3.81959275e-313, 4.94065646e-324,
        1.33021924e-311, 5.92878775e-323, 1.33021921e-311,
        4.66839106e-313, 0.00000000e+000, 0.00000000e+000,
        1.31421462e-321, 0.00000000e+000, 5.09279022e-313,
        4.94065646e-324, 1.33021924e-311, 1.08694442e-322,
        1.33021921e-311, 5.72938896e-313, 0.00000000e+000,
        0.00000000e+000, 1.50690022e-321, 0.00000000e+000,
        5.94158854e-313, 4.94065646e-324, 1.33021924e-311,
        5.92878775e-323, 1.33021921e-311, 6.79038685e-313,
        0.00000000e+000, 0.00000000e+000],
       [1.314

In [110]:
x.reshape((2,2,25)) # 2 rows 2 colume each having 25 elemnet in it

array([[[1.33021921e-311, 0.00000000e+000, 1.69759695e-313,
         4.94065646e-324, 1.33021924e-311, 5.92878775e-323,
         1.33021921e-311, 2.33419569e-313, 0.00000000e+000,
         0.00000000e+000, 1.31421462e-321, 0.00000000e+000,
         2.75859485e-313, 4.94065646e-324, 1.33021924e-311,
         1.08694442e-322, 1.33021921e-311, 3.60739317e-313,
         0.00000000e+000, 0.00000000e+000, 1.50690022e-321,
         0.00000000e+000, 3.81959275e-313, 4.94065646e-324,
         1.33021924e-311],
        [5.92878775e-323, 1.33021921e-311, 4.66839106e-313,
         0.00000000e+000, 0.00000000e+000, 1.31421462e-321,
         0.00000000e+000, 5.09279022e-313, 4.94065646e-324,
         1.33021924e-311, 1.08694442e-322, 1.33021921e-311,
         5.72938896e-313, 0.00000000e+000, 0.00000000e+000,
         1.50690022e-321, 0.00000000e+000, 5.94158854e-313,
         4.94065646e-324, 1.33021924e-311, 5.92878775e-323,
         1.33021921e-311, 6.79038685e-313, 0.00000000e+000,
         0.00

In [111]:
x=np.arange(2,20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [112]:
x=np.empty((3,3))
x

array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 5.3359090e-321],
       [0.0000000e+000, 0.0000000e+000, 3.5617543e-317]])

In [113]:
xs=np.empty((3,4,3)) ## 3 rows, each row having 4 column, and each column having 3 elements
xs

array([[[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [-2.71657325e-311,  0.00000000e+000,  0.00000000e+000]]])

In [114]:
xr=np.arange(1,101)
xr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [119]:
# w= xr.reshape()
xr.ndim

1

In [121]:
w= xr.reshape((2,50))
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [123]:
w.ndim

2

In [125]:
z=xr.reshape((4,5,5))
z

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [124]:
z.ndim

3

In [147]:
z.shape

(4, 5, 5)

In [116]:
y=xr.reshape((2,2,5,5))
print(y) ## 4 dimensional array

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]
   [ 21  22  23  24  25]]

  [[ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]
   [ 41  42  43  44  45]
   [ 46  47  48  49  50]]]


 [[[ 51  52  53  54  55]
   [ 56  57  58  59  60]
   [ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]]

  [[ 76  77  78  79  80]
   [ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]]]


In [117]:
y.ndim

4

### Arithmetic with ndarray

In [129]:
xr+xr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [136]:
xr**2

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000], dtype=int32)

In [137]:
xr>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
xr[xr>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Indexing and slicing

### indexing

In [140]:
xr[1]

2

In [141]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [142]:
w[1]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [143]:
w[1][2]

53

## Fancy indexing

In [156]:
xr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [157]:
xr[[-1,-2,-3]]

array([100,  99,  98])

In [150]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [153]:
w[1][[2,0,3]]

array([53, 51, 54])

In [148]:
w.ndim

2

In [149]:
w.shape

(2, 50)

### Slicing

In [158]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [167]:
# need odd row fist we reshape it in w their were 2 rows only that we reshape it

In [228]:
wr =w.reshape(10,10)
wr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [224]:
wr[0:10:2,::] ## got the odd rows out of 10 rows  description 0 is the start index 10 is the end index and 2 is the step size
## and rest are for column

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [231]:
## if we need only columes then 
wr[::,0:10:2] ## got odd column out of 10 descriotion 0 is the start index 10 in end and 2 is the step size

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [233]:
# or need first 4 colume
wr[::,0:4] ### note that row are all 10 but coulme are 4

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

### Game make a sqaure border ill with 1 ones and in center zeross will be thier

In [234]:
game = np.ones((5,5))
game

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [236]:
game[1:-1] ## skip 1st row we write start from 1 and skip last row we wirte -1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [239]:
# now we comes to column same as above
game[1:-1,1:-1] ## this is the center of th 5,5 sqauare

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [240]:
game[1:-1,1:-1] = 0 ## we put all valeu to zero

In [241]:
game

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [242]:
# game 2 chess board 1 0 1 0 1 0
# game 3 foot ball play ground alernate row ones and the zeros