In [1]:
import numpy as np


### nd Array

In [2]:
x =np.zeros((4,4)) # 4 ROWs and 4 Columns
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
x = np.ones((1,2)) #1 Row and 1 Columns
x

array([[1., 1.]])

In [4]:
x = np.empty((4,6))
x

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.24611674e-306, 1.29061821e-306,
        6.23057349e-307, 2.22522597e-306, 1.06810268e-306],
       [6.23052935e-307, 1.86920193e-306, 9.34608432e-307,
        2.22522597e-306, 1.33511969e-306, 8.34426039e-308]])

In [5]:
ls = [1,4,5,6]
x= np.array(ls)
x

array([1, 4, 5, 6])

In [6]:
x = np.arange(1,100,10) # prameters start stop step
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
x.shape # 10 elements ki ake array hai with 1 dimensional array

(10,)

In [8]:
x= np.empty((10,10))
x.shape

(10, 10)

In [9]:
x.reshape((2,50)) # their are 100 elements need mulipules of 100 (2,50),(2,2,5,5)

array([[1.13012384e-311, 0.00000000e+000, 3.81959244e-313,
        4.94065646e-324, 1.13012387e-311, 1.13012384e-311,
        1.13012384e-311, 5.09278991e-313, 0.00000000e+000,
        0.00000000e+000, 1.13012384e-311, 0.00000000e+000,
        5.51718907e-313, 4.94065646e-324, 1.13012387e-311,
        1.13012384e-311, 1.13012384e-311, 7.00258612e-313,
        0.00000000e+000, 0.00000000e+000, 1.31421462e-321,
        0.00000000e+000, 7.42698528e-313, 4.94065646e-324,
        1.13012387e-311, 1.08694442e-322, 1.13012384e-311,
        8.70018276e-313, 0.00000000e+000, 0.00000000e+000,
        1.50690022e-321, 0.00000000e+000, 8.91238234e-313,
        4.94065646e-324, 1.13012387e-311, 5.92878775e-323,
        1.13012384e-311, 1.35807731e-312, 0.00000000e+000,
        0.00000000e+000, 1.31421462e-321, 0.00000000e+000,
        3.81959244e-313, 4.94065646e-324, 1.13012387e-311,
        1.08694442e-322, 1.13012384e-311, 5.30498949e-313,
        0.00000000e+000, 0.00000000e+000],
       [1.506

In [10]:
x.reshape((2,2,25)) # 2 rows 2 colume each having 25 elemnet in it

array([[[1.13012384e-311, 0.00000000e+000, 3.81959244e-313,
         4.94065646e-324, 1.13012387e-311, 1.13012384e-311,
         1.13012384e-311, 5.09278991e-313, 0.00000000e+000,
         0.00000000e+000, 1.13012384e-311, 0.00000000e+000,
         5.51718907e-313, 4.94065646e-324, 1.13012387e-311,
         1.13012384e-311, 1.13012384e-311, 7.00258612e-313,
         0.00000000e+000, 0.00000000e+000, 1.31421462e-321,
         0.00000000e+000, 7.42698528e-313, 4.94065646e-324,
         1.13012387e-311],
        [1.08694442e-322, 1.13012384e-311, 8.70018276e-313,
         0.00000000e+000, 0.00000000e+000, 1.50690022e-321,
         0.00000000e+000, 8.91238234e-313, 4.94065646e-324,
         1.13012387e-311, 5.92878775e-323, 1.13012384e-311,
         1.35807731e-312, 0.00000000e+000, 0.00000000e+000,
         1.31421462e-321, 0.00000000e+000, 3.81959244e-313,
         4.94065646e-324, 1.13012387e-311, 1.08694442e-322,
         1.13012384e-311, 5.30498949e-313, 0.00000000e+000,
         0.00

In [11]:
x=np.arange(2,20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
x=np.empty((3,3))
x

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.88926250e-321],
       [1.46915600e+195, 1.46923397e+195, 7.20362222e+159]])

In [13]:
xs=np.empty((3,4,3)) ## 3 rows, each row having 4 column, and each column having 3 elements
xs

array([[[1.13010339e-311, 1.20057952e-321, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.15998412e-028],
        [2.44171989e+232, 8.00801729e+159, 9.45007090e-076],
        [1.39804329e-076, 1.05118732e-153, 1.39804329e-076]],

       [[7.57880771e-096, 1.39804329e-076, 1.39803697e-076],
        [6.01347176e-154, 1.39736881e-076, 1.21089429e-099],
        [1.30354289e-076, 2.62395837e+179, 4.24787597e-086],
        [1.83053433e-076, 1.03080384e+136, 6.01347002e-154]],

       [[1.79821556e-052, 2.63017466e-052, 9.35155177e-067],
        [3.30672796e-033, 3.93703381e-062, 7.75259436e-072],
        [2.18229367e-094, 3.98472821e+252, 1.47289889e+179],
        [9.08367237e+223, 1.16466228e-028, 4.05373402e-317]]])

In [14]:
xr=np.arange(1,101)
xr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
# w= xr.reshape()
xr.ndim

1

In [16]:
w= xr.reshape((2,50))
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
w.ndim

2

In [18]:
z=xr.reshape((4,5,5))
z

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [19]:
z.ndim

3

In [20]:
z.shape

(4, 5, 5)

In [21]:
y=xr.reshape((2,2,5,5))
print(y) ## 4 dimensional array

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]
   [ 21  22  23  24  25]]

  [[ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]
   [ 41  42  43  44  45]
   [ 46  47  48  49  50]]]


 [[[ 51  52  53  54  55]
   [ 56  57  58  59  60]
   [ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]]

  [[ 76  77  78  79  80]
   [ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]]]


In [22]:
y.ndim

4

### Arithmetic with ndarray

In [23]:
xr+xr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [24]:
xr**2

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000], dtype=int32)

In [25]:
xr>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
xr[xr>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Indexing and slicing

### indexing

In [27]:
xr[1]

2

In [28]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
w[1]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
w[1][2]

53

## Fancy indexing

In [31]:
xr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
xr[[-1,-2,-3]]

array([100,  99,  98])

In [33]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [34]:
w[1][[2,0,3]]

array([53, 51, 54])

In [35]:
w.ndim

2

In [36]:
w.shape

(2, 50)

### Slicing

In [37]:
w

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
# need odd row fist we reshape it in w their were 2 rows only that we reshape it

In [39]:
wr =w.reshape(10,10)
wr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [40]:
wr[0:10:2,::] ## got the odd rows out of 10 rows  description 0 is the start index 10 is the end index and 2 is the step size
## and rest are for column

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [41]:
## if we need only columes then 
wr[::,0:10:2] ## got odd column out of 10 descriotion 0 is the start index 10 in end and 2 is the step size

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [42]:
# or need first 4 colume
wr[::,0:4] ### note that row are all 10 but coulme are 4

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

### Game make a sqaure border ill with 1 ones and in center zeross will be thier

In [43]:
game = np.ones((5,5))
game

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
game[1:-1] ## skip 1st row we write start from 1 and skip last row we wirte -1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# now we comes to column same as above
game[1:-1,1:-1] ## this is the center of th 5,5 sqauare

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
game[1:-1,1:-1] = 0 ## we put all valeu to zero

In [47]:
game

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
# game 2 chess board 1 0 1 0 1 0
# game 3 foot ball play ground alernate row ones and the zeros

# Build-In functions numpy

In [49]:
xyz=np.array([5,8,7,4,11])
abc = np.array([2,10,22,2,3])

In [50]:
np.sqrt(xyz)

array([2.23606798, 2.82842712, 2.64575131, 2.        , 3.31662479])

In [51]:
np.power(xyz,2)

array([ 25,  64,  49,  16, 121], dtype=int32)

In [52]:
np.max(xyz)

11

In [53]:
np.maximum(xyz,abc) ## compare both array and take out max value form both but havinf both elemet lenth same

array([ 5, 10, 22,  4, 11])

### np.where function

In [54]:
salary = np.array([20000,25000,0,-1])
salaryDeatil = np.where(salary<=0,"Not Ok","OK")
salaryDeatil

array(['OK', 'OK', 'Not Ok', 'Not Ok'], dtype='<U6')

In [55]:
salary

array([20000, 25000,     0,    -1])

In [56]:
np.where(salary<=0,15000,50000)

array([50000, 50000, 15000, 15000])

# Mathematical & Statistical Methods

In [57]:
x = np.array([7,10,9,10,7,8])

In [58]:
x.mean()

8.5

In [59]:
x.cumsum() ## firt index 7 seconf index 7+10, 7+10+9 and so on....

array([ 7, 17, 26, 36, 43, 51], dtype=int32)

In [60]:
x.cumprod() ## firt index 7 seconf index 7*10, 7*10*9 and so on....

array([     7,     70,    630,   6300,  44100, 352800], dtype=int32)

In [61]:
y= x>6

In [62]:
y

array([ True,  True,  True,  True,  True,  True])

In [63]:
y.sum() ## sum all true each true = 1

6

In [64]:
y.all() ## ckeck all are true

True

In [65]:
y.any() ## check of any value is true

True

In [66]:
y=x>7
y

array([False,  True,  True,  True, False,  True])

In [67]:
y.sum()

4

In [68]:
y.any()

True

In [69]:
y.all()

False

In [70]:
arry = np.arange(15).reshape((5,3))

In [71]:
arry

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [72]:
arry.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [73]:
a = np.ones((2,3,4))

In [74]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [75]:
np.transpose(a,(1,0,2)).shape

(3, 2, 4)

In [76]:
 arr = np.arange(16).reshape((2, 2, 4))


In [77]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [78]:
 arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [79]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [80]:
 arr.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [81]:
print(arr, end="\n\n")
print(arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

(2, 2, 4)


In [82]:
print(arr.T ,end="\n\n")
print((arr.T).shape)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]

(4, 2, 2)


In [83]:
 arr.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [84]:
arr = np.random.randn(5, 3)
arr

array([[-0.25302691, -0.76895002, -0.8879464 ],
       [ 0.22721191,  1.26441759,  0.48765441],
       [-0.43051779, -1.4247326 , -1.30442937],
       [-1.53229427, -1.0876722 ,  0.37260744],
       [ 0.38056208, -2.40906469,  0.24550029]])

In [85]:
arr.sort(0)

In [86]:
arr

array([[-1.53229427, -2.40906469, -1.30442937],
       [-0.43051779, -1.4247326 , -0.8879464 ],
       [-0.25302691, -1.0876722 ,  0.24550029],
       [ 0.22721191, -0.76895002,  0.37260744],
       [ 0.38056208,  1.26441759,  0.48765441]])

In [87]:
arr = np.random.randn(2, 2)
arr

array([[ 2.05442447, -0.35861135],
       [ 0.69423868, -0.30158535]])

In [88]:
np.tile(arr)

TypeError: tile() missing 1 required positional argument: 'reps'

In [89]:
arr.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [90]:
#Swap columns 1 and 2 in the array
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [92]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [93]:
# Swap rows 1 and 2 in the array arr:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr[[0,2,1],]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [95]:
a=np.random.randint(low=5, high=10, size=(5,3))
a

array([[6, 7, 9],
       [6, 5, 7],
       [7, 6, 9],
       [7, 5, 6],
       [7, 5, 7]])

In [96]:
b=np.random.random((5,3))
b

array([[0.69007482, 0.08503338, 0.91930788],
       [0.3183412 , 0.94690429, 0.02016971],
       [0.37957998, 0.55313893, 0.19759519],
       [0.15522993, 0.5991296 , 0.02654667],
       [0.2266809 , 0.95896162, 0.31632057]])

In [97]:
a+b

array([[6.69007482, 7.08503338, 9.91930788],
       [6.3183412 , 5.94690429, 7.02016971],
       [7.37957998, 6.55313893, 9.19759519],
       [7.15522993, 5.5991296 , 6.02654667],
       [7.2266809 , 5.95896162, 7.31632057]])

In [98]:
rand_arr = np.random.uniform(5,10, size=(5,3))

In [99]:
rand_arr

array([[7.79013287, 8.80067547, 8.15539859],
       [6.55466803, 9.73442335, 6.24214699],
       [9.36422327, 6.45207126, 5.73527009],
       [7.09992066, 8.60512395, 9.15368774],
       [7.38678421, 8.75929165, 6.16087983]])

In [100]:
rand_arr[:4]

array([[7.79013287, 8.80067547, 8.15539859],
       [6.55466803, 9.73442335, 6.24214699],
       [9.36422327, 6.45207126, 5.73527009],
       [7.09992066, 8.60512395, 9.15368774]])

In [109]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)
# a[~np.na]
np.isnan(a)

[ 1.  2.  3. nan  5.  6.  7. nan]


array([False, False, False,  True, False, False, False,  True])

In [111]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [123]:
a = range(2,9)
# map(lambda x: return print(x))